# site settings
title: Paulina & Szymon
subtitle: Ślub & Wesele
email: szymow94@gmail.com
description: Zarówno ślub cywilny jak i przyjęcie weselne<br /> zostanie zoorganizowane w hotelu Jan Sander.
baseurl: "/forty-jekyll-theme" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: Wycieczkowa 2/10
city: Rąbień AB
state: 
zip_code: 95-070
country: Polska
phone: 571061910

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/szymow
  GitLab:
  Google-Plus:
  Instagram:
  LinkedIn: 
  Twitter: https://twitter.com/szymow
  Facebook:
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
